In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
def matrix_plus():
    
    m1 = np.random.randn(5,5)

    m2 = np.random.randn(5,5)
    
    print(m1+m2)

matrix_plus()

[[-0.21202214 -1.18076073  1.86055133  0.2468471   1.35131634]
 [ 0.23210895 -0.45499708 -0.52628585 -3.4444884  -2.30257784]
 [-0.45096489 -0.46847707 -0.23407651 -1.81834757  0.17098282]
 [-1.38568364 -0.11433026  0.0525951  -0.79379088 -1.58810712]
 [ 1.45442539  1.27325681  0.17459233  0.53736567 -0.53095712]]
