In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# 第一題 算閏年：

In [2]:
def year():
    
    year = input("請輸入西元某年:")
    
    year = int(year)
    
    if ((year%4==0 and year%100!=0) or (year%400==0 and year%100==0)):
        
        print("閏年")
    
    else:
        
        print("平年")

year()

請輸入西元某年:2020
閏年


# 第二題 實作五乘五矩陣的矩陣加法函式：

In [3]:
def matrix_plus():
    
    m1 = np.random.randn(5,5)

    m2 = np.random.randn(5,5)
    
    print(m1+m2)

matrix_plus()

[[-0.5971598  -0.28282932 -3.00203334 -1.46498985  2.26134815]
 [-1.17551591 -2.44722506  2.15744579 -1.59851262  1.32338872]
 [ 2.01767903 -2.69282018  0.95417006  0.90141559 -0.77306368]
 [ 0.71272658 -0.7106506  -2.1098366  -0.93439103 -0.19036794]
 [ 0.26222372 -1.79186592 -1.71872941 -0.67865509 -0.71890245]]


# 第三題 錄取分數表格:

In [4]:
up = ["國文","英文","數甲","數乙","物理","化學","生物","歷史","地理","公民","加權分數"] #columns

g = [86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6]

w = {"土語系": [2, 2, 0, 1, 0, 0, 0, 1, 1, 0],
    "財政系": [1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],
    "金融系": [1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],
    "國貿系": [1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],
    "會計系": [1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],
    "法律系": [1, 2, 0, 1, 0, 0, 0, 1, 0, 1],
    "公行系": [1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],
    "應數系": [1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],
    "教育系": [1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]}

left = [] #index

k = []

for key in w:
    
    left.append(key)
    
    e = w[key]
    
    e.append((np.array(e)*g).sum())
    
    k.append(e)
    
df = pd.DataFrame(k,index=left,columns=up)

df

國文   英文   數甲    數乙  物理  化學  生物  歷史  地理    公民     加權分數
土語系  2.0  2.0  0.0  1.00   0   0   0   1   1  0.00  589.200
財政系  1.0  1.5  0.0  1.50   0   0   0   0   0  0.00  350.350
金融系  1.0  1.5  0.0  2.00   0   0   0   0   0  0.00  398.600
國貿系  1.5  2.0  0.0  2.00   0   0   0   0   0  0.00  481.550
會計系  1.5  2.0  0.0  2.00   0   0   0   1   1  0.00  642.450
法律系  1.0  2.0  0.0  1.00   0   0   0   1   0  1.00  508.900
公行系  1.0  1.5  0.0  1.25   0   0   0   0   0  1.25  436.975
應數系  1.0  1.0  1.5  0.00   1   1   0   0   0  0.00  461.300
教育系  1.5  2.0  0.0  1.25   0   0   0   1   1  0.00  570.075

# 挑戰題一 Bubble Sort:

In [5]:
def BS(matrix):
    df = pd.DataFrame(matrix)
    df.columns = ["分數"]
    df.sort_values(by="分數", ascending=True, inplace=True)
    a = df.values.reshape(1,len(df))
    a = list(a)
    L = []
    for i in range(0,len(a)):
        L.append(a[i])
    print(L)

In [6]:
BS([14,52,98,84,65,80,78])

[array([14, 52, 65, 78, 80, 84, 98], dtype=int64)]


# 挑戰題二：自製DataFrame

In [7]:
A = [30,10,2,5,6,81]
B = [1,9,6,6,94,48]
C = np.array(A+B).reshape(2,6)
C

array([[30, 10,  2,  5,  6, 81],
       [ 1,  9,  6,  6, 94, 48]])

In [8]:
df = pd.DataFrame(C)
df

0   1  2  3   4   5
0  30  10  2  5   6  81
1   1   9  6  6  94  48

In [9]:
df.columns = ["第一場","第二場","第三場","第四場","第五場","第六場"]
df

第一場  第二場  第三場  第四場  第五場  第六場
0   30   10    2    5    6   81
1    1    9    6    6   94   48

In [10]:
df.index = range(1,3)
df

第一場  第二場  第三場  第四場  第五場  第六場
1   30   10    2    5    6   81
2    1    9    6    6   94   48